version: '1'

services:
  client:
    build: './client'
    stdin_open: true
    env_file:
      - ./client/.env
    volumes:
      - './client/src:/client/src:ro'
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    
  web:
    build: './web'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './web/src:/web/src:ro'
    ports:
      - '3000:3000'
  server:
    build: './server'
    stdin_open: true
    env_file:
      - ./server/.env
    volumes:
      - './server/src:/server/src:ro'
    ports:
      - '8000:8000'